### ISSUE TITLE
Painter plugin breaks Obsidian hotkeys functionality

### ISSUE THREAD

**Issue by dalesimpson** [KraXen72/obsidian-painter#11]
## Summary
After installing Painter v1.1.0 the hotkeys (e.g., CMD+k, CMD+i, CMD+b, CMD+n, etc.) stopped working. There were no error messages on the screen or in the console. 

**Obsidian version v1.6.5.** 

## Steps to reproduce

1. Install Painter
2. Create a new note. 
3. Add some text to the new note.
4. Highlight the text with Painter using the right-click menu.
5. Try to use a hotkey (e.g., CMD+k or CMD+n), and nothing will happen.

## Workaround Steps

1. Disable Painter
2. Quit Obsidian (this is needed so the disabled state of the Painter plugin is persisted for a later startup)
3. Restart Obsidian
4. Disable all community plugins (Obsidian will restart on its own when you do this). _At this point, after the restart, hotkey functionality will have been restored._ 
5. Enable all community plugins (Obsidian will restart again; the disabled state of the Painter plugin will be "remembered" from step 2)

At this point, the hotkeys will work again. 

## Troubleshooting notes

I disabled every Community Plugin and one-by-one turned them back on and the problem returned as soon as I enabled Painter. This is limit of the means I have available to troubleshoot this issue, otherwise, I would have gone further. 

Sorry to be the bearer of bad news. Fwiw, I was excited to use Painter and for the few hours I used it before discovering hotkey problem, I really enjoyed it.

**Comment by KraXen72** [comment]
thank you for reporting. this is already tracked in #4

**Comment by dalesimpson** [comment]
Thank you for responding so quickly. My apologies for the duplicate report. I'm afraid I didn't recognize the overlap when I looked at #4 

Thanks again for your help. I'm looking forward to using Painter again!
