### ISSUE TITLE
Plugin breaks native highlighting

### ISSUE THREAD

**Issue by jvvns** [KraXen72/obsidian-painter#14]
Hi, first of all, thank you for this plug-in! It'll come in handy for my college notes. I found a weird issue when using it: if enabled, the normal (==text==) highlighting breaks. I use the _Primary_ theme, which has different highlighting styles depending on whether the text is bolded, italicized, etc. Only the 'base' one breaks, while the rest remain intact. Here's what it looks like both with and without the _Painter_ plugin:

<img width="242" alt="Captura de pantalla 2024-09-21 a las 17 45 14" src="https://github.com/user-attachments/assets/63e533dc-f0ca-440e-9f57-70d2832dbbdd">
With Painter

<br>
<img width="256" alt="Captura de pantalla 2024-09-21 a las 17 44 56" src="https://github.com/user-attachments/assets/38163763-da09-4f59-82d6-821fd74e40f2">
Without Painter

<br>Is there anything I can do to use this plug-in without losing my previously highlighted items? Thanks!

Edit: forgot to mention, this happens regardless of the 'Overwrite previous highlights' option being enabled or not.

**Comment by KraXen72** [comment]
yes, this is an already reported issue. see #4. 
Please wait for a fix or make a pull request fixing it.
