### ISSUE TITLE
Select / update to non-default highlight style

### ISSUE THREAD

**Issue by tommyhosman** [KraXen72/obsidian-painter#2]
Great plugin!

I have two suggestions. The first being the most important for me.

### 1. Update style
It'd be great if the `highlight style` could be selected on the fly and updated.  For example, I want to use `realistic` 99% of the time, but occasionally, I want to just change the text's color.

**Suggested commands / interactions**
Through context menu, you could imagine style buttons that would not close the pop-up menu.
I could imagine also having these commands. 
1. `update-style` This would bring up style options to update the current cursor-selected highlight.
2. `paint-with-style` This command would allow you to choose style then color (maybe just brings up the context menu pop-up).

### 2. Auto switch `highlight method`
The second suggestion is about updating the highlight method.

I don't know anything about css vs inline. But if it wasn't difficult, it seems useful to have a method that would update a file between the two.

### 3. Sneaky third suggestion
Add an option to use ctrl-click to go directly to the highlight menu.

**Comment by KraXen72** [comment]
> update style and auto switch 
  
highlight style can be already update on the fly as long as you use the `css-classes` and not `inline-styles` option in the settings.
previously highlighted notes with inline styles will unfortunately not be affected, you'll have to update them or write a script to do it. Later, I might add an option to convert existing notes between the two methods.

i'll add an explanation about css vs inline to the readme.

> sneaky third suggestion
  
not a good idea, ctrl + click is a common action on stuff like links, etc. just bind the `Open Painter Menu` command to a hotkey, i have it set to ctrl + g
